# Generated by Django 4.2.4 on 2023-08-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='date_pqrs',
            field=models.DateField(db_column='fechaPqrs', default='2023-08-28', verbose_name='fecha_pqrs'),
        ),
    ]
