# Generated by Django 4.2.4 on 2023-08-28 00:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_comment='nombre Area', max_length=20, unique=True, verbose_name='nombre_areas')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_comment='Nombre Estado', max_length=20, unique='True', verbose_name='nombre_estado')),
                ('fk_id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.areas')),
            ],
        ),
        migrations.CreateModel(
            name='Sexos',
            fields=[
                ('id', models.AutoField(db_comment='Llave Primaria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_comment='Nombre del sexo', max_length=10, null=True, unique=True, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(db_comment='Llave Primaria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_comment='Nombre tipo de documento', max_length=40, unique=True, verbose_name='nombre')),
                ('siglas', models.CharField(db_comment='Abreviatura/Sigla del Tipo Documento', max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(db_column='nombres', db_comment='Nombres', max_length=30, verbose_name='nombres')),
                ('surnames', models.CharField(db_column='apellidos', db_comment='Apellidos', max_length=30, verbose_name='Apellidos')),
                ('num_doc', models.CharField(db_comment='Id tipo de documento', max_length=15, unique=True, verbose_name='num_doc')),
                ('num_tel', models.CharField(db_comment='Numero telefonico', max_length=10, unique=True, verbose_name='num_tel')),
                ('birth_date', models.DateField(db_column='fecha_nacimiento', db_comment='Fecha de Nacimiento', validators=[django.core.validators.MaxValueValidator('2023')], verbose_name='fecha_nacimiento')),
                ('email', models.EmailField(db_comment='Correo electronico', max_length=254, unique=True, verbose_name='email')),
                ('password', models.CharField(db_comment='Contraseña hasheada', max_length=255, verbose_name='password')),
                ('email_verified_at', models.DateField(db_comment='Fecha y hora de validacion de correo electronico', null=True)),
                ('remember_token', models.CharField(db_comment="token 'recuerdame'", max_length=100, null=True, verbose_name='token_recuerdame')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.estado')),
                ('fk_id_sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.sexos', verbose_name='id_sexo')),
                ('fk_id_tip_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.tipodocumento', verbose_name='id_tip_doc')),
            ],
        ),
    ]
