# Generated by Django 4.2.4 on 2023-08-29 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(db_comment='Nombre de la Categoría', max_length=50, unique=True, verbose_name='nombre de la categoría')),
                ('slug', models.CharField(db_comment='Ruta Url', max_length=100, unique=True, verbose_name='Ruta Url')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_comment='Nombre Marca', max_length=50, unique=True, verbose_name='Nombre de la marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marcas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=55, unique=True, verbose_name='modelo')),
                ('imagen_producto', models.TextField(db_column='imagen', db_comment='Imágen del producto', verbose_name='Imágen del producto')),
                ('descripcion', models.TextField(db_comment='Descripción del producto', verbose_name='Descripción')),
                ('precio', models.CharField(db_comment='Precio unitario del producto', max_length=10, verbose_name='precio')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.categorias', verbose_name='Categorias')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.marcas', verbose_name='Marcas')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UnidadesProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(db_comment='Serial Unidad del producto', max_length=255, null='False', unique=True, verbose_name='seriales')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productos')),
            ],
            options={
                'verbose_name': 'Unidad producto',
                'verbose_name_plural': 'Unidades productos',
                'db_table': 'unidades_productos',
                'ordering': ['id'],
            },
        ),
    ]
