# Generated by Django 4.2.4 on 2023-08-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'ordering': ['id'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='marcas',
            options={'ordering': ['id'], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'ordering': ['id'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='unidadesproductos',
            options={'ordering': ['id'], 'verbose_name': 'Unidad producto', 'verbose_name_plural': 'Unidades productos'},
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='fk_id_categorias',
            new_name='categorias',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='fk_id_marcas',
            new_name='marcas',
        ),
        migrations.RenameField(
            model_name='unidadesproductos',
            old_name='fk_id_producto',
            new_name='id_producto',
        ),
        migrations.AlterField(
            model_name='categorias',
            name='nombre_categoria',
            field=models.CharField(db_comment='Nombre de la Categoría', max_length=50, unique=True, verbose_name='nombre de la categoría'),
        ),
        migrations.AlterField(
            model_name='marcas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='marcas',
            name='nombre',
            field=models.CharField(db_comment='Nombre Marca', max_length=50, unique=True, verbose_name='Nombre de la marca'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(db_comment='Descripción del producto', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen_producto',
            field=models.TextField(db_column='imagen', db_comment='Imágen del producto', verbose_name='Imágen del producto'),
        ),
        migrations.AlterField(
            model_name='unidadesproductos',
            name='serial',
            field=models.CharField(db_comment='Serial Unidad del producto', max_length=255, null='False', unique=True, verbose_name='seriales'),
        ),
        migrations.AlterModelTable(
            name='marcas',
            table='marcas',
        ),
        migrations.AlterModelTable(
            name='productos',
            table='productos',
        ),
        migrations.AlterModelTable(
            name='unidadesproductos',
            table='unidades_productos',
        ),
    ]
