# Generated by Django 4.2.4 on 2023-08-28 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.AutoField(db_comment='Llave Primaria', primary_key=True, serialize=False, verbose_name='id_direcciones')),
                ('direccion', models.TextField(db_comment='Direccion de cliente', verbose_name='direccion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_id_cliente', models.ForeignKey(db_comment='Fk id cliente', on_delete=django.db.models.deletion.CASCADE, to='landing.users', verbose_name='fk_id_cliente')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEntrega',
            fields=[
                ('id', models.AutoField(db_comment='Llave Primaria', primary_key=True, serialize=False, verbose_name='id_tipo_entregas')),
                ('nombre', models.CharField(db_comment='Nombre tipo de entrega', max_length=50, unique=True, verbose_name='nombre_tipo_entrega')),
            ],
            options={
                'db_table': 'tipos_entrega',
            },
        ),
        migrations.CreateModel(
            name='FacturasVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_facturas_Venta')),
                ('fecha_venta', models.DateTimeField(unique=True, verbose_name='fecha_venta')),
                ('subtotal', models.CharField(db_comment='Subtotal factura', max_length=10, verbose_name='subtotal')),
                ('iva', models.CharField(db_comment='Valor Iva', default='1.19', max_length=10, verbose_name='valor_iva')),
                ('total', models.CharField(blank=True, db_comment='Valor total', max_length=10, verbose_name='total_factura_venta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.users', verbose_name='id_cliente')),
            ],
            options={
                'db_table': 'facturas_venta',
            },
        ),
        migrations.CreateModel(
            name='FacturasCompra',
            fields=[
                ('id', models.AutoField(db_comment='Llave Primaria', primary_key=True, serialize=False, verbose_name='id_facturas_compra')),
                ('fecha_compra', models.DateTimeField(db_comment='fecha y hora de ejecucion de la compra', unique=True)),
                ('fecha_recibido', models.DateTimeField(db_comment='Fecha  y hora recepcion del pedido', unique=True)),
                ('subtotal', models.CharField(db_comment='Subtotal factura', max_length=10, verbose_name='subtotal')),
                ('impuestos', models.CharField(db_comment='Valor impuestos', max_length=10, verbose_name='impuestos')),
                ('total', models.CharField(blank=True, db_comment='Valor total compra', max_length=10, verbose_name='total_compra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_idTrabajador', models.ForeignKey(db_column='fk_id_trabajador_solicitante', db_comment='Fk Id Trabajador que realizo la compra', on_delete=django.db.models.deletion.CASCADE, related_name='id_trabajador', to='landing.users')),
                ('fk_id_receptor', models.ForeignKey(db_comment='Fk Id Trabajador que realiza el pedido', on_delete=django.db.models.deletion.CASCADE, related_name='id_receptor', to='landing.users', verbose_name='id_receptor')),
            ],
            options={
                'db_table': 'facturas_compra',
            },
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id', models.AutoField(db_comment='Llave Primaria', primary_key=True, serialize=False, verbose_name='id_entregas')),
                ('fecha_entrega', models.DateTimeField(db_comment='Fecha y hora de entrega', verbose_name='fecha_entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_id_direccion', models.ForeignKey(db_comment='Fk id direcciones xd', on_delete=django.db.models.deletion.CASCADE, to='facturation.direcciones', verbose_name='id_direccion')),
                ('fk_id_factura', models.ForeignKey(db_comment='Fk Id Factura', on_delete=django.db.models.deletion.CASCADE, to='facturation.facturasventa', verbose_name='id_factura')),
                ('fk_id_tipo_entrega', models.ForeignKey(db_comment='FK id tipo de entrega', on_delete=django.db.models.deletion.CASCADE, to='facturation.tipoentrega', verbose_name='id_tipo_entrega')),
                ('fk_id_trabajador', models.ForeignKey(db_comment='Fk id trabajador', on_delete=django.db.models.deletion.CASCADE, to='landing.users', verbose_name='id_trabajador')),
                ('unidades_compras', models.ManyToManyField(related_name='unidades_compras', to='inventory.unidadesproductos')),
            ],
        ),
    ]
