# Generated by Django 4.2.4 on 2023-08-28 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('landing', '0001_initial'),
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregas',
            name='unidades_compras',
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='fk_id_cliente',
            field=models.ForeignKey(db_column='fk_id_cliente', db_comment='Fk id cliente', on_delete=django.db.models.deletion.CASCADE, to='landing.users', verbose_name='fk_id_cliente'),
        ),
        migrations.CreateModel(
            name='UnidadesCompras',
            fields=[
                ('id', models.AutoField(db_comment='Llave Primaria', primary_key=True, serialize=False, verbose_name='id_unidades_compras')),
                ('fk_id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.facturasventa', verbose_name='fk_id_factura')),
                ('fk_id_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unidadesproductos', verbose_name='fk_id_unidad')),
            ],
            options={
                'db_table': 'unidades_compras',
            },
        ),
        migrations.AddField(
            model_name='facturasventa',
            name='unidades_compras',
            field=models.ManyToManyField(related_name='unidades_compras', through='facturation.UnidadesCompras', to='inventory.unidadesproductos'),
        ),
    ]
